### ISSUE TITLE
TypeError: Cannot read property 'indexes' of undefined

### ISSUE THREAD

**Issue by emlai** [ozum/pg-structure#22] opened 2019-03-06 00:29 UTC
First of all, thanks for this awesome library, it's just what I was looking for.

I suddenly started getting the following error when my database structure got more complex. When I call `await pgStructure({ database: 'test_db' })`, I get:

```
TypeError: Cannot read property 'indexes' of undefined
    at C:\Users\emlai\src\dbviz\node_modules\pg-structure\lib\pg-structure.js:142
    at res.rows.forEach.row (C:\Users\emlai\src\dbviz\node_modules\pg-structure\lib\pg-structure.js:70)
    at Array.forEach (<anonymous>)
    at fs.readFile.then.then.res (C:\Users\emlai\src\dbviz\node_modules\pg-structure\lib\pg-structure.js:70)
    at process._tickCallback (internal/process/next_tick.js:68)
```

Using pg-structure v4.2.2.

Here's the dump of the database that reproduces this for me:

<details><summary>Database dump</summary>

```sql
--
-- PostgreSQL database dump
--

-- Dumped from database version 11.2
-- Dumped by pg_dump version 11.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: Order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Order" (
    id integer NOT NULL,
    orderdate timestamp without time zone NOT NULL,
    ordernumber character varying(10),
    customerid integer NOT NULL,
    totalamount numeric(12,2) DEFAULT 0
);


ALTER TABLE public."Order" OWNER TO postgres;

--
-- Name: customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer (
    id integer NOT NULL,
    firstname character varying(40) NOT NULL,
    lastname character varying(40) NOT NULL,
    city character varying(40),
    country character varying(40),
    phone character varying(20)
);


ALTER TABLE public.customer OWNER TO postgres;

--
-- Name: orderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orderitem (
    id integer NOT NULL,
    orderid integer NOT NULL,
    productid integer NOT NULL,
    unitprice numeric(12,2) DEFAULT 0 NOT NULL,
    quantity integer DEFAULT 1 NOT NULL
);


ALTER TABLE public.orderitem OWNER TO postgres;

--
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    id integer NOT NULL,
    productname character varying(50) NOT NULL,
    supplierid integer NOT NULL,
    unitprice numeric(12,2) DEFAULT 0,
    package character varying(30),
    isdiscontinued boolean DEFAULT false NOT NULL
);


ALTER TABLE public.product OWNER TO postgres;

--
-- Name: supplier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.supplier (
    id integer NOT NULL,
    companyname character varying(40) NOT NULL,
    contactname character varying(50),
    contacttitle character varying(40),
    city character varying(40),
    country character varying(40),
    phone character varying(30),
    fax character varying(30)
);


ALTER TABLE public.supplier OWNER TO postgres;

--
-- Data for Name: Order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Order" (id, orderdate, ordernumber, customerid, totalamount) FROM stdin;
\.


--
-- Data for Name: customer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customer (id, firstname, lastname, city, country, phone) FROM stdin;
\.


--
-- Data for Name: orderitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orderitem (id, orderid, productid, unitprice, quantity) FROM stdin;
\.


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product (id, productname, supplierid, unitprice, package, isdiscontinued) FROM stdin;
\.


--
-- Data for Name: supplier; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.supplier (id, companyname, contactname, contacttitle, city, country, phone, fax) FROM stdin;
\.


--
-- Name: Order Order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Order"
    ADD CONSTRAINT "Order_pkey" PRIMARY KEY (id);


--
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);


--
-- Name: orderitem orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orderitem
    ADD CONSTRAINT orderitem_pkey PRIMARY KEY (id);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- Name: supplier supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT supplier_pkey PRIMARY KEY (id);


--
-- Name: Order fk_order_reference_customer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Order"
    ADD CONSTRAINT fk_order_reference_customer FOREIGN KEY (customerid) REFERENCES public.customer(id);


--
-- Name: orderitem fk_orderite_reference_order; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orderitem
    ADD CONSTRAINT fk_orderite_reference_order FOREIGN KEY (orderid) REFERENCES public."Order"(id);


--
-- Name: orderitem fk_orderite_reference_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orderitem
    ADD CONSTRAINT fk_orderite_reference_product FOREIGN KEY (productid) REFERENCES public.product(id);


--
-- Name: product fk_product_reference_supplier; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fk_product_reference_supplier FOREIGN KEY (supplierid) REFERENCES public.supplier(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

GRANT USAGE ON SCHEMA public TO emlai;


--
-- Name: TABLE "Order"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public."Order" TO emlai;


--
-- Name: TABLE customer; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.customer TO emlai;


--
-- Name: TABLE orderitem; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.orderitem TO emlai;


--
-- Name: TABLE product; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.product TO emlai;


--
-- Name: TABLE supplier; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.supplier TO emlai;


--
-- PostgreSQL database dump complete
--


```

</details>

---

It started working again after I granted some privileges:

```sql
GRANT USAGE ON SCHEMA public TO emlai;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO emlai;
```

And after I revoke the privileges I get the same error again:

```sql
REVOKE USAGE ON SCHEMA public FROM emlai;
REVOKE SELECT ON ALL TABLES IN SCHEMA public FROM emlai;
```

But even after granting the privileges, pg-structure doesn't seem to return the foreign key constraint info.

**Comment by ozum** [comment] 2019-03-06 06:07
Hi,

I cannot recreate example dump, because of `stdin` in `COPY public.orderitem (id, orderid, productid, unitprice, quantity) FROM stdin;`

Not related the error you got, but `Order` table starts with an upper case letter whereas other tables start with lower case letters. If it isn't by design, it may be a typo, considering PostgreSQL is case sensitive.

For the error, please test with an admin - super user, if error goes away, it may be related to privileges.

If you are sure it is not related to privileges, please provide a working schema and a sample `js` code which produces given error. Then I'll check it.

**Comment by ozum** [comment] 2019-05-17 15:25
I'm closing issue, because I cannot reproduce it, and no more details are provided for long time. In case you need further help, please open another case and provide details.

**Closed by ozum** 2019-05-17 15:25 UTC
